# .github/workflows/chromatic.yml

name: "Chromatic"

on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install dependencies
#        run: npm
#        # ðŸ‘‡ Adds Chromatic as a step in the workflow
#      - name: Publish to Chromatic
#        uses: chromaui/action@v1
#        # Chromatic GitHub Action options
#        with:
#          token: ${{ env.GITHUB_SHA_SHORT }}
#          # ðŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
#          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
